# Generated by Django 4.0.2 on 2022-02-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obhavo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="O'zbekcha nomi", max_length=100)),
                ('city', models.CharField(help_text='Inglizcha nomi', max_length=100)),
                ('lot', models.FloatField(help_text='latitude - geografik kenglik')),
                ('lan', models.FloatField(help_text='longitude - geografik uzunlik')),
            ],
        ),
    ]
