MAINS = {
    "Clear":"Ochiq",
    "Clouds":"Bulutli",
    "Thunderstorm":"Momaqaldiroq",
    "Drizzle":"Yomg'ir",
    "Rain":"Yomg'ir",
    "Snow":"Qor",
    "Mist":"Tuman",
    "Smoke":"Tutun",
    "Haze":"Tuman",
    "Dust":"Chang",
    "Fog":"Tuman",
    "Sand":"Qum",
    "Ash":"Dovul",
    "Squall":"Bo'ron",
    "Tornado":"Tornado"
}

ICONS = {
    "01d":"вЂпёЏ",
    "02d":"рџЊ¤",
    "03d":"вЃпёЏ",
    "04d":"вЃпёЏ",
    "09d":"рџЊ§",
    "10d":"рџЊ¦",   
    "11d":"рџЊ©",
    "13d":"вќ„пёЏ",
    "50d":"рџЊ«",
    "01n":"рџЊ•",
    "02n":"вЃпёЏ",
    "03n":"вЃпёЏ",
    "04n":"вЃпёЏ",
    "09n":"рџЊ§",
    "10n":"рџЊ§",   
    "11n":"рџЊ©",
    "13n":"вќ„пёЏ",
    "50n":"рџЊ«"       
}

DESCRIPTIONS = {
    "clear sky":"musaffo osmonli",
    'few clouds':"ozgina bulutli",
    'light rain':"yengil yomg'ir",
    'moderate rain': "mo'tadil yomg'ir",
    'heavy intensity rain': "kuchli yomg'ir",
    'very heavy rain': "juda kuchli yomg'ir",
    'extreme rain': "jala",
    'freezing rain': "muzli yomg'ir, do'l",
    'light intensity shower rain': "yengil intensivlikdagi yomg'ir",
    'shower rain': "jala",
    'heavy intensity shower rain': "kuchli jala",
    'ragged shower rain': "kuchli yomg'ir",
    'light snow': "yengil qor",
    'Snow': "yengil qor",
    'Heavy snow': "kuchli qor",
    'Sleet': "qorli yomg'ir",
    'Light shower sleet': "yengil yomg'irli qor",
    'Shower sleet': "qor-yomg'ir",
    'Light rain and snow': "yengil yomg'ir va qor",
    'Rain and snow': "yomg'ir va qor",
    'Light shower snow': "yengil yomg'irli qor",
    'Shower snow': "yomg'irli qor",
    'Heavy shower snow': "kuchli yomg'irli qor",
    'mist': "tumanli xiralik",
    'Smoke': "tumanli xiralik",
    'Haze': "tumanli xiralik",
    'sand/ dust whirls': "qum/chang",
    'fog': "tumanli xiralik",
    'sand': "chang/qum",
    'dust': "chang-to'zon",
    'volcanic ash': "vulqon kuli",
    'squalls': "yaxshigina bo'ron",
    'tornado': "kuchli tornado",
    'few clouds: 11-25%': "ozgina bulutli: 11-25%",
    'scattered clouds: 25-50%': "pag'a-pag'a bulutli: 25-50%",
    'broken clouds: 51-84%': "qalin bulutli: 51-84%",
    'overcast clouds: 85-100%': "qora bulutli: 85-100%",
    "thunderstorm with light rain":"ozgina yomg'irli momaqaldiroq",
    "thunderstorm with rain":"yomg'irli momaqaldiroq",
    "thunderstorm with heavy rain":"kuchli yomg'irli momaqaldiroq",
    "light thunderstorm":"yengil momaqaldiroq",
    "thunderstorm":"momaqaldiroq",
    "heavy thunderstorm":"kuchli momaqaldiroq",
    "scattered clouds":"pag'a-pag'a bulutli",
    "overcast clouds":"qora bulutli",
    "broken clouds":"qalin bulutli",
    "ragged thunderstorm":"yomg'irli momaqaldiroq",
    "thunderstorm with light drizzle":"momaqaldiroq, yengil yomg'ir",
    "thunderstorm with drizzle":"yomg'irli momaqaldiroq",
    "thunderstorm with heavy drizzle":"momaqaldiroq kuchli yog'ingarchilik bilan",
    "light intensity drizzle":"o'rtacha chaqmoq",
    "drizzle":"yog'ingarchilik",
    "heavy intensity drizzle":"kuchli chaqmoq",
    "light intensity drizzle rain":"yengil chaqmoq bilan yomg'ir",
    "drizzle rain":"yomg'ir yog'ishi",
    "heavy intensity drizzle rain":"kuchli shiddatli yomg'ir",
    "shower rain and drizzle":"dushdek yomg'ir va yog'ingarchilik",
    "heavy shower rain and drizzle":"kuchli yomg'ir va yog'ingarchilik"
}

DEGS = {
    "0":"Shimol",
   "45":"Shimoliy-Sharq",
   "90":"Sharq",
   "135":"Janubiy-Sharq",
   "180":"Janub",
   "225":"Janubiy-G'arb",
   "270":"G'arb",
   "315":"Shimoliy-G'arb",
   "360":"Shimol"
}